### ISSUE TITLE
Fix access checking

### ISSUE THREAD

**Issue by sashabaranov** [skygrid/disneyland#4]
[Current](https://github.com/skygrid/disneyland/blob/44b9f77bdbe99ec246a19656ff365b50f065ee20/disneyland/server.go) access checking is wrong in multiple ways

* Users with access to ANY project and specific kind cannot pull jobs without specifying project
* Same users category can create jobs in any project

So, users(kind=ANY, project=X) and workers(kind=X, project=ANY) should have following access rights to rpc's

* `CreateJob`
    * **users** — Can create jobs in their project
    * **workers** — Cannot create jobs
* `GetJob`
    * **users** — Can get jobs
    * **workers** — Can get jobs with proper kind
* `ListJobs`
    * **users** — Can list jobs by kind in their project
    * **workers** — Cannot list jobs
* `ModifyJob`
    * **users** — Can modify jobs in their project
    * **workers** — Can modify jobs with proper kind
* `PullPendingJobs`
    * **users** — Can pull jobs from their project
    * **workers** — Can pull jobs with proper kind

We also need tests for this.

**Comment by andreiSaw** [comment]
fixed in #5
